[package]
name = "containtment_check"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
winnow = "0.7.13"
scraper = "0.24"
anyhow = "1.0"
regex = "1.11"
